baseURL = "https://smitop.com/"
languageCode = "en-CA"
title = "Smitop's Blog"
author = "Smitop"

[taxonomies]
  tag = "tags"

[markup]
[markup.tableOfContents]
endLevel = 10
ordered = false
startLevel = 2

[related]
includeNewer = true
threshold = 30
toLower = false
[[related.indices]]
name = 'description'
weight = 80
[[related.indices]]
name = 'title'
weight = 60
[[related.indices]]
name = 'tags'
weight = 40
[[related.indices]]
name = 'date'
weight = 5
